// This code was generated by a tool. Any changes made manually will be lost
// the next time this code is regenerated.
// Generated: Thu, 19 May 2016 07:32:07 GMT
 
using System.Reflection;
 
[assembly: AssemblyVersion("3.1.19619.0")]
[assembly: AssemblyFileVersion("3.1.19619.732")]